openapi: 3.0.3
info:
  title: Daily Journal
  version: v1.0
paths:
  /accounts:
    x-controller: accounts
    post:
      x-operation: createAccount
      tags:
        - Accounts
      summary: Create an account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - firstname
                - lastname
                - email
                - password
              properties:
                firstname:
                  type: string
                lastname: 
                  type: string
                email:
                  type: string
                password:
                  type: string
                  format: password
                  minLength: 4
            example:
              firstname: Andrew
              lastname: Thibaudeau
              email: example@email.com
              password: password
      responses:
        201:
          description: Account created
        400:
          description: Invalid request
        409:
          description: Account already exists
  /accounts/{email}:
    x-controller: accounts
    parameters:
      - $ref: '#/components/parameters/PathEmail'
    delete: 
      x-operation: deleteAccount
      tags:
        - Accounts
      security:
        - cookieAuth: []
      summary: Delete an account
      responses:
        204: 
          description: Account deleted
        401:
          description: Not authenticated
        403:
          description: Access denied
    put:
      x-operation: updatePassword
      tags:
        - Accounts
      security:
        - cookieAuth: []
      summary: Update user password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - password
              properties:
                password:
                  type: string
                  format: password
                  minLength: 4
            example:
              password: new-password
      responses:
        200:
          description: Password updated
        400:
          description: Invalid request
        401:
          description: Not authenticated
        403:
          description: Access denied
        404:
          description: Account not found
  /authentication/login:
    x-controller: authentication
    put:
      x-operation: login
      tags:
        - Authentication
      summary: Login to an account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - password
              properties:
                password:
                  type: string
                  format: password
                  minLength: 4
            example:
              password: a-password
      responses:
        200:
          description: Account logged in
        400:
          description: Invalid request
        401:
          description: Not authenticated
        404:
          description: Account does not exist
  /authentication/logout:
    x-controller: accounts
    put:
      x-operation: logout
      tags:
        - Authentication
      summary: Logout of an account
      responses:
        200:
          description: Account logged out
        400:
          description: Invalid request
  /entries:
    get:
      x-operation: getEntries
      tags: 
        - Entries
      security:
        - cookieAuth: []
      summary: Get entries
      parameters:
        - name: topic
          in: query
          schema:
            type: string
        - name: week
          in: query
          schema:
            type: string
            format: date-time
        - name: month
          in: query
          schema:
            type: string
            format: date-time
        - name: year
          in: query
          schema:
            type: string
            format: date-time
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Entries'
        400:
          description: Invalid request
        401:
          description: Not authenticated
  /entries/{promptid}:
    x-controller: entries
    parameters:
      - $ref: '#/components/parameters/PathPromptid'
    post:
      x-operation: submitEntry
      tags:
        - Entries
      security:
        - cookieAuth: []
      summary: Submit an entry
      requestBody:
        $ref: '#/components/requestBodies/MakeEntry'
      responses:
        201:
          description: Entry submitted
        400:
          description: Invalid request
        401:
          description: Not authenticated
  /entries/{entryid}:
    x-controller: entries
    parameters:
      - $ref: '#/components/parameters/PathEntryid'
    put:
      x-operation: updateEntry
      tags:
        - Entries
      security:
        - cookieAuth: []
      summary: Update an entry
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - text
              properties:
                text:
                  type: string
      responses:
        200:
          description: Entry updated
        400:
          description: Update failed
        401:
          description: Not authenticated
        403:
          description: Access denied
        404: 
          description: Entry not found
    delete:
      x-operation: deleteEntry
      tags:
        - Entries
      security:
        - cookieAuth: []
      summary: Delete an entry
      responses:
        204:
          description: Entry deleted
        401:
          description: Not authenticated
        403:
          description: Access denied
components:
  parameters:
    PathEmail:
      name: email
      in: path
      required: true
      schema:
        type: string
    PathEntryid:
      name: entryid
      in: path
      required: true
      schema:
        type: string
    PathPromptid:
      name: promptid
      in: path
      required: true
      schema:
        type: string
  requestBodies:
    MakeEntry:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                entryid:
                  type: string
                  readOnly: true
                text:
                  type: string
                date:
                  type: string
                  format: date-time
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: journalSessionId
  schemas:
    GetEntry:
      type: object
      properties:
        promptid:
          type: string
          readOnly: true
        prompttext:
          type: string
          readOnly: true
        topic:
          type: string
          readOnly: true
        entryid:
          type: string
          readOnly: true
        text:
          type: string
        date:
          type: string
          format: date-time
    Entries:
      type: array
      items:
        $ref: '#/components/schemas/GetEntry'
          
