openapi: 3.0.3
info:
  title: Daily Journal
  version: v1.0
paths:
  /accounts:
    x-controller: accounts
    post:
      x-operation: createAccount
      tags:
        - Accounts
      summary: Create an account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - firstName
                - lastName
                - email
                - password
              properties:
                firstName:
                  type: string
                lastName: 
                  type: string
                email:
                  type: string
                password:
                  type: string
                  format: password
            example:
              firstName: Andrew
              lastName: Thibaudeau
              email: example@email.com
              password: password
      responses:
        201:
          description: Account created
        400:
          description: Account already exists
  /accounts/{userId}:
    x-controller: accounts
    parameters:
      - $ref: '#/components/parameters/PathUserId'
    delete: 
      x-operation: deleteAccount
      tags:
        - Accounts
      summary: Delete an account
      responses:
        204: 
          description: Account deleted
        404:
          description: Account not found
  /accounts/{userId}/login:
    x-controller: accounts
    parameters:
      - $ref: '#/components/parameters/PathUserId'
    put:
      x-operation: login
      tags:
        - Accounts
      summary: Login to an account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - password
              properties:
                password:
                  type: string
                  format: password
            example:
              password: a-password
      responses:
        200:
          description: Account logged in
        400:
          description: Login failed
        401:
          description: Password required
        403:
          description: Email and password do not match
        404:
          description: Account does not exist
  /accounts/{userId}/logout:
    x-controller: accounts
    parameters:
        - $ref: '#/components/parameters/PathUserId'
    put:
      x-operation: logout
      tags:
        - Accounts
      summary: Logout of an account
      responses:
        200:
          description: Account logged out
        400:
          description: Logout failed
  /accounts/{userId}/settings:
    x-controller: accounts
    parameters:
      - $ref: '#/components/parameters/PathUserId'
    put:
      x-operation: updatePassword
      tags:
        - Accounts
      summary: Update user password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - password
              properties:
                password:
                  type: string
                  format: password
            example:
              password: new-password
      responses:
        200:
          description: Password updated
  /entries:
    x-controller: entries
    post:
      x-operation: submitEntry
      tags:
        - Entries
      summary: Submit an entry
      parameters:
        - $ref: '#/components/schemas/MakeEntry'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - promptId
                - entryId
                - text
                - date
              properties:
                promptId:
                  type: string
                  readOnly: true
                entryId:
                  type: string
                  readOnly: true
                text:
                  type: string
                date:
                  type: string
                  format: date-time
      responses:
        201:
          description: Entry submitted
        400:
          description: Submission failed, response text required
    get:
      x-operation: getEntries
      tags: 
        - Entries
      summary: Get entries
      parameters:
        - name: topic
          in: query
          schema:
            type: string
        - name: week
          in: query
          schema:
            type: string
            format: date-time
        - name: month
          in: query
          schema:
            type: string
            format: date-time
        - name: year
          in: query
          schema:
            type: string
            format: date-time
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Entries'
  /entries/{entryId}:
    x-controller: entries
    parameters:
      - $ref: '#/components/parameters/PathEntryId'
    put:
      x-operation: updateEntry
      tags:
        - Entries
      summary: Update an entry
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - text
              properties:
                text:
                  type: string
      responses:
        200:
          description: Entry updated
        404: 
          description: Entry not found
        400:
          description: Update failed
    delete:
      x-operation: deleteEntry
      tags:
        - Entries
      summary: Delete an entry
      responses:
        204:
          description: Entry deleted
        404:
          description: Entry not found
components:
  parameters:
    PathUserId:
      name: userId
      in: path
      required: true
      schema:
        type: string
    PathEntryId:
      name: entryId
      in: path
      required: true
      schema:
        type: string
  schemas:
    MakeEntry:
      type: object
      properties:
        promptId:
            type: string
            readOnly: true
        entryId:
          type: string
          readOnly: true
        text:
          type: string
        date:
          type: string
          format: date-time
    GetEntry:
      type: object
      properties:
        promptId:
          type: string
          readOnly: true
        promptText:
          type: string
          readOnly: true
        topic:
          type: string
          readOnly: true
        entryId:
          type: string
          readOnly: true
        text:
          type: string
        date:
          type: string
          format: date-time
    Entries:
      type: array
      items:
        $ref: '#/components/schemas/GetEntry'
          
